### ISSUE TITLE
Offer custom property tokens to autocomplete

### ISSUE THREAD

**Issue by WoodyWoodsta** [atom/language-css#103]
**Expected behavior:** Custom properties (`--custom-property-123`) should be offered for the `autocomplete-plus` Symbol Provider

**Actual behavior:** Custom properties are not listed by autocomplete

### Versions

Atom `1.15.0`

**Comment by 50Wliu** [comment]
I can't reproduce.  Here's an example I took from [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables).
![image](https://cloud.githubusercontent.com/assets/2766036/22432570/541f5296-e6e3-11e6-90e0-2ae55b8927c3.png)
The variable in `:root` is tokenized as `variable.css` while the one in background-color is `variable.argument.css`.

**Comment by Alhadis** [comment]
> **Actual behavior:** Custom properties are not tokenized

@WoodyWoodsta In what sense did you mean "tokenised"? That word has special meaning with relation to language grammars, and is chiefly related to syntax highlighting. Did you mean to say "custom properties are not listed by autocomplete"?

If not, I fail to see how highlighting is connected with autocomplete suggestions.

**Comment by WoodyWoodsta** [comment]
@Alhadis You're correct. The variables are tokenised correctly. They were not, however, showing up in autocomplete. I have corrected the original post.

@50Wliu I stand to be corrected, but the use of `--main-bg-color` in the CSS `var` function falls under the `variable.argument.css` scope, but also under the `meta.function.variable.css`, which should be caught by the `.variable.css` selector?
