### ISSUE TITLE
CSS Auto Indentation not working

### ISSUE THREAD

**Issue by DijitulLiam** [atom/language-css#106]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Indentation with: {}, [], () do not work using the CSS syntax.

### Steps to Reproduce

1. Create a new blank file
2. Change the langauge to Atom's default 'CSS' syntax.
3. Create a simple CSS rule

*Where '|' is the I-cursor in Atom, and the indentation setting is set to 'Tabs (4 wide)'...*

**Expected behavior:**

.cssrule'{
'''|
}

**Actual behavior:**

.cssrule'{
|
}

**Reproduces how often:**

This happens for me 100% of the time, in my normal work environment and in safe mode.

### Versions

Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information

Auto indentation is enabled in the settings, and works for all other langauges I use.

I for some reason, have two 'CSS' languages when changing, although neither work.

![two 'CSS' languages](https://cloud.githubusercontent.com/assets/22833343/23998475/287e44ac-0a4d-11e7-928f-f811d91aa62c.png)

**Comment by 50Wliu** [comment]
Thank you for your issue!

I noticed that your image does not seem to be taken in safe mode.  Do the duplicate CSS languages still appear even in safe mode?

**Comment by Alhadis** [comment]
@DijitulLiam Could you also include a list of which packages you have installed? Just run this in Terminal, and copy+paste the output:

~~~bash
apm ls --installed
~~~

It sounds like you may have another CSS package installed which is shadowing the "real" CSS grammar in the selection list (e.g., selecting the second `css` entry will select the first entry that's named `css`).

**Comment by DijitulLiam** [comment]
Hi guys,

Thanks for getting back, and apologies for the late reply.

![image](https://cloud.githubusercontent.com/assets/22833343/24093445/c335d22a-0d4b-11e7-9473-9165be4675d0.png)

The duplicate CSS languages isn't an issue in safe mode, but the issue still persists.

![image](https://cloud.githubusercontent.com/assets/22833343/24093466/df3f4f14-0d4b-11e7-9de1-4c2f3631360e.png)

@Alhadis 
├── atom-alignment@0.12.1
├── atom-beautify@0.29.17
├── atom-material-syntax@1.0.2
├── atom-material-syntax-dark@0.2.7
├── atom-material-syntax-light@0.4.6
├── atom-material-ui@1.3.9
├── atom-ternjs@0.18.2
├── atom-wrap-in-tag@0.6.0
├── auto-detect-indentation@1.3.0
├── autocomplete-xml@0.9.4
├── busy-signal@1.3.0
├── emmet@2.4.3
├── file-icons@2.0.17
├── file-types@0.5.5
├── fonts@2.0.0
├── intentions@1.1.2
├── language-babel@2.56.2
├── linter@2.1.0
├── linter-htmlhint@1.3.2
├── linter-php@1.3.1
├── linter-ruby@1.2.5
├── linter-ui-default@1.2.1
├── linter-xo
├── markdown-preview-plus@2.4.9
├── minimap@4.26.8
├── minimap-highlight-selected@4.5.0
├── pigments@0.39.0
├── project-manager@3.3.3
├── sort-lines@0.14.0
├── white-cursor@0.7.0
└── xml-formatter@0.10.0

**Comment by 50Wliu** [comment]
Can you confirm that the bracket-matcher package is enabled?

**Comment by DijitulLiam** [comment]
bracket-matcher is installed, disabling it however doesn't fix the issue.

**Comment by Alhadis** [comment]
Do you have any strange keybindings attached to the <kbd>Enter</kbd> (or <kbd>Return</kbd>) key, perchance? Anything that might be overriding the default `editor:newline` command?

**Comment by DijitulLiam** [comment]
Unless one of the packages installed has this effect, no. I haven't personally changed anything like that.

**Comment by 50Wliu** [comment]
Hmm.  This is really weird.  Not sure what else to try.

**Comment by DijitulLiam** [comment]
It's only CSS that's the issue which is the reason it's throwing me off, as all other languages are fine.

**Comment by DijitulLiam** [comment]
I've now also checked my language's again, and I now have a duplicate of all CSS related languages apart from "styled CSS"

![image](https://cloud.githubusercontent.com/assets/22833343/24152109/99c5540e-0e42-11e7-9a37-543c7259ff93.png)

![image](https://cloud.githubusercontent.com/assets/22833343/24152213/e811405a-0e42-11e7-8955-37a5546fbc23.png)

I'm going to do a full uninstall, re-install (including packages) to see if this is the issue, and find out exactly where this CSS issue is coming from.

**Comment by DijitulLiam** [comment]
Hey again, done a full reinstall, removing all packages from Atom itself, then going ahead and removing the .atom folder completely just to make sure.

The issue has gone, so I can only assume this was a package specific problem, this is my new package list. (Ended up dropping a few due to house cleaning, not needing).

├── atom-material-ui@1.3.9
├── auto-detect-indentation@1.3.0
├── busy-signal@1.3.0
├── emmet@2.4.3
├── file-icons@2.0.17
├── intentions@1.1.2
├── language-babel@2.57.0
├── linter@2.1.0
├── linter-php@1.3.2
├── linter-ui-default@1.2.1
├── markdown-preview-plus@2.4.9
├── minimap-pigments@0.2.2
├── pigments@0.39.1
└── project-manager@3.3.3

**Comment by 50Wliu** [comment]
Ok, glad that it's working again.  If it happens again, please comment here and we'll keep investigating.

**Comment by BWPanda** [comment]
I've started experiencing this too. The same as what @DijitulLiam described: CSS files don't indent automatically, though all other file types do.

![Peek 2019-06-20 15-04](https://user-images.githubusercontent.com/2385329/59847996-c2796f00-936c-11e9-84ac-239b1596f3a5.gif)

I mainly use `.scss` files, so I haven't noticed this issue before now. But I've been working directly with `.css` files recently and this is getting annoying. Please let me know what information you need from me to debug/reproduce.

**Comment by 50Wliu** [comment]
@BWPanda can you please open a new issue?

**Comment by BWPanda** [comment]
@50Wliu I found the issue: I had disabled the core `language-source` package. Re-enabling it fixed the issue for me.

I see this as a bug though, so I've created a bug report here: https://github.com/atom/language-css/issues/162
