### ISSUE TITLE
Inconsistent syntax highlighting of transition properties

### ISSUE THREAD

**Issue by flachware** [atom/language-css#109]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Using different keywords as `transition-property` results in different syntax highlighting.

### Steps to Reproduce

1. Use the syntax theme 'One Light'.
2. Create a CSS file.
3. Add the following code:

```css
div {
  transition-property: width;
}

div {
  transition-property: color;
}

div {
  transition-property: background;
}
```
**Expected behavior:** [What you expect to happen]

The keywords `width`, `color` and `background` should have the same syntax highlighting.

**Actual behavior:** [What actually happens]

![bildschirmfoto 2017-03-22 um 10 54 50](https://cloud.githubusercontent.com/assets/419747/24263913/e88919fa-0ffe-11e7-8513-5b5110409a2e.png)
![bildschirmfoto 2017-03-22 um 10 55 19](https://cloud.githubusercontent.com/assets/419747/24263917/ea42b120-0ffe-11e7-84db-67d2cc207f1c.png)
![bildschirmfoto 2017-03-22 um 10 55 36](https://cloud.githubusercontent.com/assets/419747/24263919/ebbb4bd4-0ffe-11e7-901b-354391527420.png)

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

Versions

Atom : 1.15.0
Electron: 1.3.13
Chrome : 52.0.2743.82
Node : 6.5.0

apm 1.15.3
npm 3.10.5
node 4.4.5 x64
python 2.7.10
git 2.10.1

### Additional Information

[MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_animated_properties) lists `background` as an animated property, it also works in all browsers I have tested so far. Therefore I think it should not be highlighted as invalid. At least `width` and `color` I would suspect to have the same syntax highlighting.

**Comment by yanxiaobo** [comment]
same problem

**Comment by ilessiivi** [comment]
The case insensitive flag on the regex in [grammars/css.cson#L625](https://github.com/atom/language-css/blob/v0.42.2/grammars/css.cson#L625) seems to be the cause of this issue (there's a ```Background``` in the pattern next line).

Removing the case insensitive flag would fix the incorrectly identified deprecation of ```background``` as a ```transition-property``` but would cause other issues when the deprecated CSS2 system colors might not get detected. It was allowed by the [spec](http://www.w3.org/TR/css3-color/#css2-system) to use these system colors as all lowercase too.

A better solution would be to rewrite the regex in question to match the scenarios in which the deprecated CSS2 system colors might have been used. Unfortunately I'm not familiar enough with the grammar syntax or the deprecated spec to do this.

Another solution could be dropping off the CSS2 system color detection as irrelevant. I don't have any statistics to back this up, but these system color properties probably weren't very widely used, and they certainly aren't today.

I was going to create a PR to remove the case insensitive flag from the regex, but perhaps this needs a bit more discussion first.
