### ISSUE TITLE
Add support for display: flow-root

### ISSUE THREAD

**Issue by praveenpuglia** [atom/language-css#115]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

`flow-root` is a new CSS value that's available for the `display` property. It should be part of the package to provide autocompletion.

**Comment by Alhadis** [comment]
Where did you read that?

**Comment by thomasjo** [comment]
> Where did you read that?

https://developer.mozilla.org/en-US/docs/Web/CSS/display

**Comment by Alhadis** [comment]
Just checking this wasn't another Facebook thing, what with its "Flow" and all.

And the `flow-root` must've been added to that page recently (as in, since #99).

God only knows what else is missing.

**Comment by 50Wliu** [comment]
Value autocompletion is handled by https://github.com/adobe/brackets/blob/master/src/extensions/default/CSSCodeHints/CSSProperties.json.  If you would like `flow-root` and friends to be available for autocompletion, you'll need to submit a PR to that repository.

**Comment by praveenpuglia** [comment]
@50Wliu So VSCode seems to be using this package. Hence updating at brackets side will help propagate changes everywhere?
