### ISSUE TITLE
Missing CSS Grid selectors?

### ISSUE THREAD

**Issue by eivindml** [atom/language-css#116]
Looks like there are some missing CSS selectors regarding the css grid property. A lot of stuff around grids are highlighted incorrectly. 

<img width="487" alt="screen shot 2017-05-14 at 10 39 19" src="https://cloud.githubusercontent.com/assets/202450/26032351/a1c17ccc-3891-11e7-8a69-39647bd736d1.png">

**Comment by 50Wliu** [comment]
Closing, because as discovered in https://github.com/atom/language-sass/issues/210#issuecomment-301340013, these properties have already been added.
