### ISSUE TITLE
No support for 'hover' keyword in media queries

### ISSUE THREAD

**Issue by andyrichardson** [atom/language-css#128]
**About**
The hover keyword is not declared in the grammar's media-features.

**Effected packages**
Dependent package [atom/language-scss](https://github.com/atom/language-scss)

**Screenshot**
![screenshot from 2017-10-25 16-52-04](https://user-images.githubusercontent.com/10779424/32008729-d960c496-b9a4-11e7-8989-9d5b5ed3f286.png)
*Note how 'hover' is greyed out*

![screenshot from 2017-10-25 16-51-27](https://user-images.githubusercontent.com/10779424/32008697-c5e698f0-b9a4-11e7-94d3-19da7a6d4d97.png)
*Example of supported media features*

**Sources**
[Mozilla Developers: CSS Hover](https://developer.mozilla.org/en-US/docs/Web/CSS/%40media/hover)

**Comment by matteobertoldo** [comment]
@aminya can you update the Atom core with this merge and create a new tag?
as you can see the last tag (more than a year ago) has [4 commits] more (https://github.com/atom/language-css/releases/tag/v0.44.4) from the latest version...

And this repo have a lot of unclosed PR with important highlightnings for the css/scss code. Thanks!

**Comment by darangi** [comment]
Hi @matteobertoldo, thanks for bringing this to our attention. I will look into this and release a new tag

**Comment by darangi** [comment]
I will go ahead and close this issue since the related PR has been merged. Thanks!
