### ISSUE TITLE
[css] add coloring of @apply support

### ISSUE THREAD

**Issue by aeschli** [atom/language-css#130]
It looks like themes are not respecting the new @apply rules, at least in regards to color-coding.
![screen shot 2016-12-16 at 9 58 51 am](https://cloud.githubusercontent.com/assets/13442851/21273215/81c83eae-c390-11e6-8587-db99f0308e1f.png)

```css
.toolbar > .title {
  @apply --toolbar-title-theme;
}
```

**Comment by aeschli** [comment]
Syntax coloring is not provided by vscode-css-languageservice but by a text mate grammar.

**Comment by aeschli** [comment]
_From @philippelesaux on December 27, 2016 13:45_

Thank you @aeschli for moving this to the appropriate project!

**Comment by 50Wliu** [comment]
The `@apply` rule is still in the Editor's Draft stage and unapproved.  It also has [no browser support](https://caniuse.com/#feat=css-apply-rule), nor a page [on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@apply).  Until it receives wider support, language-css will not be recognizing it as a valid at-rule.
