### ISSUE TITLE
Some grid stuff (grid-area, justify-items, justify-self) missing

### ISSUE THREAD

**Issue by adcar** [atom/language-css#131]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Some grid properties are missing. Not sure if I'm missing some, I just noticed these after looking at [CSS-Tricks](https://css-tricks.com/snippets/css/complete-guide-grid/).

[grid-area](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-area)
[justify-items](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-items)
[justify-self](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-self)

Example screenshot:
![screenshot_20171212_194727](https://user-images.githubusercontent.com/13227184/33916208-b1a43194-df75-11e7-9692-38ca8415637e.png)

**Comment by 50Wliu** [comment]
Looks like grid-area has been added by justify-items/self are still missing.

**Comment by adcar** [comment]
@50Wliu Only problem with grid-area is that the name of the area (`example` in this case) is greyed out.

**Comment by abaracedo** [comment]
I created a PR for adding support to `justify-items` and `justify-self`.
