### ISSUE TITLE
Add support for justify-content: space-evenly

### ISSUE THREAD

**Issue by hacknug** [atom/language-css#135]
### Description
`space-evenly` is a new CSS value that's available for the `justify-content` property. It should be part of the package to provide syntax highlighting.

**Comment by 50Wliu** [comment]
Note that this package only provides syntax highlighting and not autocompletion.  If `space-evenly` is not autocompleting please file an issue at https://github.com/adobe/brackets asking for https://github.com/adobe/brackets/blob/master/src/extensions/default/CSSCodeHints/CSSProperties.json to be updated.

**Comment by Alhadis** [comment]
I made a PR. Will fix when my laptop is reconnected to the Internet.

**Comment by hacknug** [comment]
Sorry for that. I've edited the issue to remove the autocompletion part. What I really was looking for was syntax highlighting.

Thanks for the quick response, guys!
