### ISSUE TITLE
let's add missing mso- attribute values to the inline CSS spec

### ISSUE THREAD

**Issue by revelt** [atom/language-css#138]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Currently, some `mso-...` inline CSS attribute values are not recognised. @webtobesocial compiled all the prefixes in a [Gist here](https://gist.github.com/webtobesocial/ac9d052595b406d5a5c1).

In practice, this issue means Outlook proprietary inline CSS attributes, used in email template development currently don't get highlighted correctly, for example:

<img width="508" alt="screen shot 2018-03-23 at 14 39 18" src="https://user-images.githubusercontent.com/8344688/37835404-00b60a60-2ea8-11e8-995a-9b4f0bac124f.png">

In the example above, I'd expect `mso-line-height-rule`'s value to be highlighted same colour as `float`'s.

### Steps to Reproduce

`exactly` will be highlighted differently from `left`:

```html
<table width="100%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td style="mso-line-height-rule: exactly; text-align: left;">
      example
    </td>
  </tr>
</table>
```

**Expected behavior:**

Values of proprietary mso attributes should be recognised and coloured same way like others, for example, `left` in `text-align: left`.

**Actual behavior:**

Atom is colouring unrecognised values differently, depending on the theme.

### Versions

Atom    : 1.26.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.0
python 2.7.10
git 2.16.2

macOS HighSierra: 10.13.4

### Additional Information

https://gist.github.com/webtobesocial/ac9d052595b406d5a5c1 contains the list of all proprietary `mso` attributes.

PS. issue originally posted on https://github.com/atom/language-html/issues/192

**Comment by darangi** [comment]
Thanks for reporting this.

This issue has been resolved in the latest version of this package, I will go ahead to close this and feel free to reopen if you think otherwise
