### ISSUE TITLE
CSS Syntax Highlighting: Do not interpret inside resource locators

### ISSUE THREAD

**Issue by stonecrusher** [atom/language-css#145]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I come from reporting a syntax highlighting bug in github (was sent to linguist and from linguist to here) so I don't have Atom at all.

Example code:

```css
@-moz-document domain("images.example.com"),
               domain('imagehost.com'),
               url-prefix(https://example.com/images),
               url(https://www.example.com/test.html),
               regexp("http://www\\.example\\.(com|de|org)/images/.*")  {
    /* background-color: green !important; */
}
```
Screenshot:
![screenshot_2018-07-11](https://user-images.githubusercontent.com/1388389/42570158-47716d52-8513-11e8-9bc5-309e8f7a148c.png)

Inside resource locators there shouldn't be anything highlighted at all. Wrong purple highlighting for the first three resources, obvious wrong highlighting for the regexp one.

The double escaping comes from one escaping backslash for regexp, one more for css syntax.

### Steps to Reproduce

No need to reproduce, just look at the code posted above on github via standard desktop browser.

**Expected behavior:** Resource locators should be highlighted as one entity, everything between the `( )` in same color

**Actual behavior:** Resource locators become partly and randomly highlighted

**Reproduces how often:** Always

### Versions

I have no Idea what version they are using.

GitHub support quote:

> Every couple of weeks or so, Linguist does a new release with grammar updates, and shortly after the release happens you'll see that reflected on GitHub.com

**Comment by darangi** [comment]
Thanks for reporting this

This issue has been fixed in the latest version of this package. I will go ahead to close this and feel free to re-open it if you think otherwise
