### ISSUE TITLE
Pls. Add suport forr css scroll-snap

### ISSUE THREAD

**Issue by professorchen06** [atom/language-css#148]
Please Add suport for scroll-snap.
Here is the Documentation from Google: https://developers.google.com/web/updates/2018/07/css-scroll-snap

**Comment by abaracedo** [comment]
This should be asked on the autocomplete CSS package.

I created this https://github.com/adobe/brackets/pull/14555 for adding the autocompletion for `scroll-snap-type`.

**Comment by jbrew138** [comment]
The `scroll-snap-align` property also appears to be missing from the grammar.
