### ISSUE TITLE
Continued maintenance of the TextMate grammar

### ISSUE THREAD

**Issue by octref** [atom/language-css#159]
Hi, this is Pine from VS Code team. I'm aware that Atom has switched over to tree-sitter for highlighting CSS, and I'm wondering if Atom team will continue to take care of the CSS TextMate grammar.

I have forked https://github.com/octref/language-css to use it in VS Code. I thought about upstreaming my changes, but it seems the PRs aren't being reviewed. Also, people might miss my updated fork, although some do find it and send [PR](https://github.com/octref/language-css/pulls?q=is%3Apr+is%3Aclosed) to there.

If you do plan to make language-css mainly for the tree-sitter grammar, do you mind me redirecting people to my fork for their PRs?

@maxbrunsfeld @50Wliu

**Comment by rsese** [comment]
Hey @octref :wave:  Just wanted to let you know that someone from the team will reach out to talk about this in more detail.

**Comment by octref** [comment]
Ping, my email is easily findable from my bio.

I'd like to keep one repo up-to-date instead of having to fork and maintain.

**Comment by rsese** [comment]
Circling back to close this out since there was discussion offline and @octref now has commit on the repo :v:
