### ISSUE TITLE
Do not mark min-device-width as `invalid.deprecated`

### ISSUE THREAD

**Issue by octref** [atom/language-css#163]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

For below CSS code:

```css
@media (min-device-width: 100px) {}
```

`min-device-width` is marked as `invalid.deprecated.media.css`. Although Atom is already on tree-sitter and it doesn't mark it as `invalid.deprecated`, other editors such as VS Code does. This causes an unpleasant highlighting:

![image](https://user-images.githubusercontent.com/4033249/67342249-97ec1e00-f4e6-11e9-84b4-18c55cd5b0e3.png)

[Sublime's documentation](https://www.sublimetext.com/docs/3/scope_naming.html) also states:

![image](https://user-images.githubusercontent.com/4033249/67342277-a5090d00-f4e6-11e9-908e-7d519fe1a66e.png)

I suggest making the scope `support.type.property-name.media.css`, as people might be working with older language. This also makes it consistent with tree-sitter's CSS grammar as it doesn't mark it as invalid/deprecated:

![image](https://user-images.githubusercontent.com/4033249/67342409-f44f3d80-f4e6-11e9-8531-0ed351d3df96.png)

I can work on a PR if that change is fine for you, @maxbrunsfeld and @rsese.

### Additional Information

Originally posted at https://github.com/microsoft/vscode/issues/62515

**Comment by rsese** [comment]
Thanks @octref :+1:   We'll share this with the other maintainers and see what they think.

**Comment by lee-dohm** [comment]
@octref Yep, a PR for this would be great!

**Comment by octref** [comment]
The PR is at https://github.com/atom/language-css/pull/165. @rsese should I ask someone to review, or should I review it myself 😅
