### ISSUE TITLE
Add in @-ms-viewport and @-o-viewport to CSS grammar

### ISSUE THREAD

**Issue by emilgoldsmith** [atom/language-css#176]
## Summary

Adding in `@-ms-viewport` and `@-o-viewport` to the CSS grammar

## Motivation

Because it currently breaks syntax highlighting if you use these selectors in my editor (VSCode), and I'm sure others using this grammar too.

I am aware that it is a deprecated selector. The main reason for still including it in ones code is being backwards compatible with IE etc. I would say, though I'm far from an expert on the viewport area

## Describe alternatives you've considered

I don't see many other alternatives than living with broken syntax highlighting, or not including these tags, but as I see it there isn't a possibility that gets you both syntax highlighting and the backwards compatibility with old browsers utilizing these features.  If there is I'd be happy to hear about it!

**Comment by jpcastberg** [comment]
^^ opened pull request, plz have a look!
