### ISSUE TITLE
Key binding for comments should insert cursor within comment

### ISSUE THREAD

**Issue by caleb531** [atom/language-css#25]
Hi,

Apologies for the long title. The bug is actually quite simple: when I prepare to add a comment via Atom's default key binding (`cmd+/` for me), the text cursor is not placed *within* the comment as I would expect (so I can begin typing). Instead, the cursor is placed *after* the comment, which I find rather unintuitive.

*Before:*  
![before](https://cloud.githubusercontent.com/assets/872474/7287217/60d99a18-e907-11e4-9894-b62d177c1303.png)

*After:*  
![after](https://cloud.githubusercontent.com/assets/872474/7287241/88825aa0-e907-11e4-8607-f65423cd5f12.png)

*What I was expecting:*  
![ideal](https://cloud.githubusercontent.com/assets/872474/7287256/b1c6c9f0-e907-11e4-93ea-8b4fe09aafa0.png)

Could this be fixed?

Thanks,
Caleb

**Comment by eddiemonge** [comment]
This also affects .md files as well as probably lots of others.

**Comment by 50Wliu** [comment]
@caleb531 Can you please move this issue over to atom/atom? Your bug happens with any language that uses comments that have a start and end component (CSS, HTML, etc).

**Comment by caleb531** [comment]
Sure! Is there some GitHub function for moving issues, or do I need to simply recreate it on atom/atom?

**Comment by 50Wliu** [comment]
You can try github-issue-mover.appspot.com, though that might be just for people with write access.  If it doesn't work, just recreate it :).

**Comment by caleb531** [comment]
You're supposition is correct. It seems can only move issues for repos for which I have write access. Time to recreate!

Thanks for the help, @50Wliu. :)
Caleb
