### ISSUE TITLE
Syntax highlighting broken for values that contain negative integers.

### ISSUE THREAD

**Issue by Dentosal** [atom/language-css#29]
![screen shot 2015-06-27 at 11 35 31](https://cloud.githubusercontent.com/assets/2204863/8391190/67ff1d2a-1cc1-11e5-8d27-031024d37da3.png)

Specs:
Atom 1.0
language-css 0.32.0
Mac OS X 10.9

**Comment by AntonTrollback** [comment]
The `padding-left` thing here is probably an other issue?
![negative](https://cloud.githubusercontent.com/assets/520365/8429297/9bcae7ee-1f26-11e5-87cb-c19006b73a92.png)

**Comment by burodepeper** [comment]
I've solved both the `preserve-3d` and `padding-left` issue.
I think there are more property-value constants missing, so I'll research them before creating a pull request.

**Comment by burodepeper** [comment]
Fixed in pull request #38
