### ISSUE TITLE
Syntax highlighting broken for some attribute selectors

### ISSUE THREAD

**Issue by jwdallas** [atom/language-css#31]
See the screenshot below.

![screen shot 2015-06-29 at 12 21 16 pm](https://cloud.githubusercontent.com/assets/1310725/8416273/7d086d4a-1e59-11e5-81a1-7720f5ec0bdc.png)

The code in the screenshot confuses the syntax highlighter:

```CSS
[disabled],
[disabled] + p {
    /* styles */
}
```

**Comment by AntonTrollback** [comment]
![disabled](https://cloud.githubusercontent.com/assets/520365/8429269/4eed4b56-1f26-11e5-9864-04a0b0e212e1.png)

**Comment by burodepeper** [comment]
I've created a patch that fixes these issues, see below:

![schermafbeelding 2015-08-18 om 14 36 56](https://cloud.githubusercontent.com/assets/3703530/9330019/9bf77c80-45b6-11e5-9360-7b8b398ed455.png)

**Comment by burodepeper** [comment]
Fixed in pull request #38

**Comment by jamesscholeyweb** [comment]
+1  Is this fix going to get merged? #9348
