### ISSUE TITLE
End of rule not being highlighted correctly

### ISSUE THREAD

**Issue by kevinsawicki** [atom/language-css#34]
```css
#foo { color: #666 }
#bar { display: none }
```

Using one dark syntax:

<img width="243" alt="screen shot 2015-07-29 at 3 38 14 pm" src="https://cloud.githubusercontent.com/assets/671378/8971713/d633566c-3607-11e5-95e6-653ef93df892.png">

This was working in 1.0.2 but not in 1.0.3.

I think this may have been cause by https://github.com/atom/language-css/commit/37fac708ea5b5c18267187997f2ca3af44f7b645 /cc @benogle

**Comment by kevinsawicki** [comment]
Adding a `;` to the first rule does fix it:

<img width="239" alt="screen shot 2015-07-29 at 3 40 16 pm" src="https://cloud.githubusercontent.com/assets/671378/8971742/25161792-3608-11e5-96f5-7e3f93e980e4.png">

**Comment by mrdoob** [comment]
👌
