### ISSUE TITLE
Single line comments using //

### ISSUE THREAD

**Issue by SINE** [atom/language-css#35]
Single Line Comments aren't colored properly, they should be treated the same way as any actual CSS parser handles them (everything after them to be treated as commented out).

![atom-singlelinecomment](https://cloud.githubusercontent.com/assets/11297260/9096386/1520fd42-3bbd-11e5-9ed5-d0eaf6ec7ecb.jpg)

**Comment by benogle** [comment]
Single line comments are `/* comment here */` in CSS. See http://stackoverflow.com/questions/12298890/is-it-bad-practice-to-comment-out-single-lines-of-css-with

**Comment by SINE** [comment]
Sorry, you're wrong here.
// is known as a next construct comment in CSS.
You may be right in it not being supported by W3C, but please consider this article:
http://creativeandcode.com/the-crappy-state-of-css-commenting/

**Comment by SINE** [comment]
// is known as a next construct comment in CSS.
You may be right in it not documented by W3C, but please consider this article by Atkins Jr. - a member at the CSS Working Group:
http://www.xanthir.com/b4U10
