### ISSUE TITLE
`text-overflow` is not highlighted

### ISSUE THREAD

**Issue by devoncarew** [atom/language-css#41]
`text-overflow` is not highlighted:

<img width="243" alt="screen shot 2015-10-08 at 11 38 10 am" src="https://cloud.githubusercontent.com/assets/1269969/10376126/17870b8c-6db1-11e5-9643-d0e6284cb8ec.png">

https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow

(this is for a `.less` file)

**Comment by izuzak** [comment]
> (this is for a .less file)

Seems like this should be opened over at https://github.com/atom/language-less -- it looks fine if I set the language to CSS, but doesn't look okay if I set the language to LESS.

Also, I think this was added to the LESS language grammar in https://github.com/atom/language-less/commit/d0104dedb652c8343bed3f55196c8040df4113e1, but was afterwards (accidentally?) removed in https://github.com/atom/language-less/pull/16.

Recommendation: open a new issue in that repository and ping the author of that pull request to see what was the motivation behind that change.
