### ISSUE TITLE
Add support for media queries level 4

### ISSUE THREAD

**Issue by colinmeinke** [atom/language-css#47]
As a syntax theme author I would love support for [media queries level 4](https://drafts.csswg.org/mediaqueries/#custom-mq) which allows the following syntax in CSS:

`@custom-media --small-viewport ( min-width: 450px );`

It would be great to get the `at-rule` class for `@custom-media` and the `variable` class for `--small-viewport` so I can style consistently between CSS, Sass and Less.

**Comment by esdoppio** [comment]
This feature has been deferred to [level 5](https://github.com/w3c/csswg-drafts/blob/3abb7e30e5a7ec5f7504f5bc6470cf3c9a123b37/mediaqueries/deferred-for-level-5.txt), which is not even a draft yet—it's not guaranteed to exist in the future, and this is not valid CSS atm.

/cc @50Wliu

**Comment by 50Wliu** [comment]
Thanks @esdoppio.
