### ISSUE TITLE
Which CSS properties should be added?

### ISSUE THREAD

**Issue by dstorey** [atom/language-css#5]
I’ve put together a list of CSS properties: http://ref.openweb.io/CSS/ . 

There are a lot more than are included in language-css.cson . However, not every property is implemented, and the nature of standards work means some will get renamed or dropped.

Is there a policy (or should there be?) of what gets included? If Atom gets auto-updated regularly like Chrome does, I think we can be more flexible on adding and removing CSS properties that are not set in stone.  Or maybe a good policy would be just to include features that are supported by at least one browser?

If we decide what should be added, I can work on making a pull request with the properties that are missing.

**Comment by jplatte** [comment]
+1

In particular, the flexbox layout stuff is (supported in all major browsers)[http://caniuse.com/#feat=flexbox] by now and not highlighted in Atom.

Another thing, which I saw isn't on that list @dstorey linked to: http://www.w3.org/TR/css3-sizing/

**Comment by kevinsawicki** [comment]
Since this issue was opened there has been a steady stream of additions and removals so I think we should just continue to follow that process as properties change over time, closing this out.
