### ISSUE TITLE
text-overflow is not syntax highlighted properly

### ISSUE THREAD

**Issue by Ben3eeE** [atom/language-css#56]
### Prerequisites

* [X] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [X] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

I was checking out the css file of backgridjs and noticed that `text-overflow` was not syntax highlighted properly, the file can be found on github: https://github.com/wyuenho/backgrid/blob/master/lib/backgrid.css

As recommended in the Atom slack channel I tested `Editor: Log Cursors Scopes` on error lines and correct lines and all report the same message.

```
Scopes at Cursor

source.css
meta.property-list.css
meta.property-value.css
punctuation.terminator.rule.css
```

There are some additional properties not syntax highlighted in this file. I don't know if any of this is valid css, see images.

![text-overflow](https://cloud.githubusercontent.com/assets/1058982/15794253/c765729c-29e9-11e6-8bf7-779e0dceeb2b.PNG)
![webkit trans](https://cloud.githubusercontent.com/assets/1058982/15794254/c9877818-29e9-11e6-87ce-477e89c2287c.PNG)
![table cell](https://cloud.githubusercontent.com/assets/1058982/15794255/cb04fcec-29e9-11e6-8c51-a1e7df737638.PNG)

cc @50Wliu 

**Expected behavior:** Syntax highlighting is correct because `text-overflow` appears to be a valid css property https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow.

**Actual behavior:** text-overflow is not correctly syntax highlighted.

### Versions

Atom 1.7.4
Windows 10

**Comment by 50Wliu** [comment]
text-overflow fixed by #59.  Please open new issues for the remaining highlighting problems.
