### ISSUE TITLE
Possible to avoid maintaining duplicate feature lists?

### ISSUE THREAD

**Issue by dstorey** [atom/language-css#6]
CSS properties are listed in:

[support.type.property-name.css](https://github.com/atom/language-css/blob/master/grammars/css.cson#L348)
AND
[.source.css .meta.property-list:not(.meta.property-value)](https://github.com/atom/language-css/blob/master/scoped-properties/language-css.cson#L94)

CSS property values are listed in:

[support.constant.property-value.css](https://github.com/atom/language-css/blob/master/grammars/css.cson#L264)
AND
[.source.css .meta.property-value](https://github.com/atom/language-css/blob/master/scoped-properties/language-css.cson#L267)

HTML elements are listed in:

[entity.name.tag.css](https://github.com/atom/language-css/blob/master/grammars/css.cson#L376)
AND
[.source.css:not(.meta.property-list)](https://github.com/atom/language-css/blob/master/scoped-properties/language-css.cson#L6)

Not to mention any lists of HTML elements and such in the language-html file.

This is going to be a pain to maintain and will easily go out of sync. Is there some way each can be defined once and pulled into both places?

**Comment by silvenon** [comment]
What about JSON file(s) which would be used as data embedded in grammar files? I don't think there's a way to dynamically pull data from other files, so there would have to be a source template and a generated file.

**Comment by kevinsawicki** [comment]
This is not currently possible and the lists have evolved pretty well over the last year to stay updated and consistent.
